# fly.toml app configuration file generated for westgate-tab on 2023-06-27T12:47:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "westgate-tab"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
